### ISSUE TITLE
A question about the code of Discriminator in ./src/imputeByGans.py

### ISSUE THREAD

**Issue by GoldJinJin** [xuyungang/scIGANs0.1.1#4]
Hello! Xu, When I browse your model code, I find the code of Discriminator(line 187-275) has input dimension   **(batchsize,1,32,32)** but output dimension    **(batchsize,1,1,1)**(a pixel?). 

I found that the input dimension and the output dimension of the discriminator written in your paper is **(batch,1,32,32)** and  **(batchsize,1,32,32)**,then calculate the loss.

I have a question about this, I hope you can take the time to answer this question when you see it, thank you very much！

**Comment by xuyungang** [comment]
Thank you for your feedback. Please contact the other first author of this work, Zhigang Zhang zzg@hbue.edu.cn, who is in charge of the model development. Thank you.
